import {
    CurrentOrder,
    Order,
    OrderProductsInformation,
    OrderStatus,
    PaymentMethods,
    SelfPickUp,
} from '../../../api/orderAPI';
import { ProductTypes } from '../../../api/productsAPI';
import { Recipient } from '../../../components/pages/PlacingAnOrder/Recipient/Recipient';
import { actions, orderReducer } from '../../../redux/order/orderReducer';

const initialState = {
    orders: [] as Order[],
    currentOrder: {
        products: [] as OrderProductsInformation[],
        receivingMethod: {} as Recipient | SelfPickUp,
        city: '',
        payMethod: '' as PaymentMethods,
        recipient: {} as Recipient,
    } as CurrentOrder,
    isCompleted: false,
    currentPage: 0,
    pageSize: 10,
};

describe('test order reducer', () => {
    it('test set orders', () => {
        const action = actions.setOrders([
            {
                id: 1,
                date: new Date(2021, 5, 12),
                history: [
                    {
                        date: new Date(2021, 5, 12),
                        status: OrderStatus.CREATED,
                    },
                    {
                        date: new Date(2021, 5, 14),
                        status: OrderStatus.ACCEPTED_FOR_PROCESSING,
                    },
                    {
                        date: new Date(2021, 5, 16),
                        status: OrderStatus.IS_GOING_TO,
                    },
                    {
                        date: new Date(2021, 5, 17),
                        status: OrderStatus.ACCEPTED_FOR_DELIVERY,
                    },
                    {
                        date: new Date(2021, 5, 18),
                        status: OrderStatus.IS_DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.COMPLETED,
                    },
                ],
                products: [
                    {
                        id: 1,
                        title: 'product1',
                        img: 'productImg',
                        type: ProductTypes.ACCESSORIES,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 30,
                        statusList: ['Новинка'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product product product',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                ],
            },
            {
                id: 2,
                date: new Date(2021, 5, 12),
                history: [
                    {
                        date: new Date(2021, 5, 12),
                        status: OrderStatus.CREATED,
                    },
                    {
                        date: new Date(2021, 5, 14),
                        status: OrderStatus.ACCEPTED_FOR_PROCESSING,
                    },
                    {
                        date: new Date(2021, 5, 16),
                        status: OrderStatus.IS_GOING_TO,
                    },
                    {
                        date: new Date(2021, 5, 17),
                        status: OrderStatus.ACCEPTED_FOR_DELIVERY,
                    },
                    {
                        date: new Date(2021, 5, 18),
                        status: OrderStatus.IS_DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.COMPLETED,
                    },
                ],
                products: [
                    {
                        id: 1,
                        title: 'product1',
                        img: 'productImg',
                        type: ProductTypes.ACCESSORIES,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 30,
                        statusList: ['Новинка'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product product product',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                ],
            },
            {
                id: 3,
                date: new Date(2021, 5, 12),
                history: [
                    {
                        date: new Date(2021, 5, 12),
                        status: OrderStatus.CREATED,
                    },
                    {
                        date: new Date(2021, 5, 14),
                        status: OrderStatus.ACCEPTED_FOR_PROCESSING,
                    },
                    {
                        date: new Date(2021, 5, 16),
                        status: OrderStatus.IS_GOING_TO,
                    },
                    {
                        date: new Date(2021, 5, 17),
                        status: OrderStatus.ACCEPTED_FOR_DELIVERY,
                    },
                    {
                        date: new Date(2021, 5, 18),
                        status: OrderStatus.IS_DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.COMPLETED,
                    },
                ],
                products: [
                    {
                        id: 1,
                        title: 'product1',
                        img: 'productImg',
                        type: ProductTypes.ACCESSORIES,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 30,
                        statusList: ['Новинка'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product product product',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                ],
            },
            {
                id: 4,
                date: new Date(2021, 5, 12),
                history: [
                    {
                        date: new Date(2021, 5, 12),
                        status: OrderStatus.CREATED,
                    },
                    {
                        date: new Date(2021, 5, 14),
                        status: OrderStatus.ACCEPTED_FOR_PROCESSING,
                    },
                    {
                        date: new Date(2021, 5, 16),
                        status: OrderStatus.IS_GOING_TO,
                    },
                    {
                        date: new Date(2021, 5, 17),
                        status: OrderStatus.ACCEPTED_FOR_DELIVERY,
                    },
                    {
                        date: new Date(2021, 5, 18),
                        status: OrderStatus.IS_DELIVERED,
                    },
                ],
                products: [
                    {
                        id: 1,
                        title: 'product1',
                        img: 'productImg',
                        type: ProductTypes.ACCESSORIES,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 30,
                        statusList: ['Новинка'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product product product',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                ],
            },
            {
                id: 5,
                date: new Date(2021, 5, 12),
                history: [
                    {
                        date: new Date(2021, 5, 12),
                        status: OrderStatus.CREATED,
                    },
                    {
                        date: new Date(2021, 5, 14),
                        status: OrderStatus.ACCEPTED_FOR_PROCESSING,
                    },
                    {
                        date: new Date(2021, 5, 16),
                        status: OrderStatus.IS_GOING_TO,
                    },
                    {
                        date: new Date(2021, 5, 17),
                        status: OrderStatus.ACCEPTED_FOR_DELIVERY,
                    },
                    {
                        date: new Date(2021, 5, 18),
                        status: OrderStatus.IS_DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.COMPLETED,
                    },
                ],
                products: [
                    {
                        id: 1,
                        title: 'product1',
                        img: 'productImg',
                        type: ProductTypes.ACCESSORIES,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 30,
                        statusList: ['Новинка'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product product product',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                ],
            },
            {
                id: 6,
                date: new Date(2021, 5, 12),
                history: [
                    {
                        date: new Date(2021, 5, 12),
                        status: OrderStatus.CREATED,
                    },
                    {
                        date: new Date(2021, 5, 14),
                        status: OrderStatus.ACCEPTED_FOR_PROCESSING,
                    },
                    {
                        date: new Date(2021, 5, 16),
                        status: OrderStatus.IS_GOING_TO,
                    },
                    {
                        date: new Date(2021, 5, 17),
                        status: OrderStatus.ACCEPTED_FOR_DELIVERY,
                    },
                    {
                        date: new Date(2021, 5, 18),
                        status: OrderStatus.IS_DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.DELIVERED,
                    },
                    {
                        date: new Date(2021, 5, 20),
                        status: OrderStatus.COMPLETED,
                    },
                ],
                products: [
                    {
                        id: 1,
                        title: 'product1',
                        img: 'productImg',
                        type: ProductTypes.ACCESSORIES,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 30,
                        statusList: ['Новинка'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product product product',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                    {
                        id: 2,
                        title: 'product2',
                        img: 'productImg',
                        type: ProductTypes.ELECTRIC_BICYCLE,
                        grade: 2,
                        price: 1000,
                        commentsCount: 12,
                        promotionPercent: 20,
                        statusList: ['Новинка', 'Хит продаж'],
                    },
                ],
            },
        ]);
        const newState = orderReducer(initialState, action);

        expect(newState.orders.length).toBe(6);
    });

    it('test set products in current order', () => {
        const action = actions.setProducts([
            {
                id: 1,
                title: 'product1',
                img: 'productImg',
                type: ProductTypes.ACCESSORIES,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 30,
                statusList: ['Новинка'],
                count: 1,
            },
            {
                id: 2,
                title: 'product2',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_BICYCLE,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка', 'Хит продаж'],
                count: 1,
            },
            {
                id: 3,
                title: 'product3',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_CAR,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка'],
                count: 1,
            },
            {
                id: 4,
                title: 'product4',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_CAR,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка'],
                count: 1,
            },
            {
                id: 5,
                title: 'product5',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_CAR,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка'],
                count: 1,
            },
        ]);
        const newState = orderReducer(initialState, action);

        expect(newState.currentOrder.products.length).toBe(5);
    });

    it('test delete product from current order', () => {
        const actionSetProducts = actions.setProducts([
            {
                id: 1,
                title: 'product1',
                img: 'productImg',
                type: ProductTypes.ACCESSORIES,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 30,
                statusList: ['Новинка'],
                count: 1,
            },
            {
                id: 2,
                title: 'product2',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_BICYCLE,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка', 'Хит продаж'],
                count: 1,
            },
            {
                id: 3,
                title: 'product3',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_CAR,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка'],
                count: 1,
            },
            {
                id: 4,
                title: 'product4',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_CAR,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка'],
                count: 1,
            },
            {
                id: 5,
                title: 'product5',
                img: 'productImg',
                type: ProductTypes.ELECTRIC_CAR,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 20,
                statusList: ['Новинка'],
                count: 1,
            },
        ]);
        let newState = orderReducer(initialState, actionSetProducts);

        const actionDeleteProduct = actions.deleteProduct(1);
        newState = orderReducer(newState, actionDeleteProduct);

        expect(newState.currentOrder.products.length).toBe(4);
    });

    it('test increase product with id 1 in current order', () => {
        const actionSetProducts = actions.setProducts([
            {
                id: 1,
                title: 'product1',
                img: 'productImg',
                type: ProductTypes.ACCESSORIES,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 30,
                statusList: ['Новинка'],
                count: 3,
            },
        ]);
        let newState = orderReducer(initialState, actionSetProducts);

        const actionDecreaseProduct = actions.increaseProduct(1);
        newState = orderReducer(newState, actionDecreaseProduct);

        expect(
            newState.currentOrder.products.find((product) => product.id === 1)
                ?.count,
        ).toBe(4);
    });

    it('test decrease product with id 1 in current order', () => {
        const actionSetProducts = actions.setProducts([
            {
                id: 1,
                title: 'product1',
                img: 'productImg',
                type: ProductTypes.ACCESSORIES,
                grade: 2,
                price: 1000,
                commentsCount: 12,
                promotionPercent: 30,
                statusList: ['Новинка'],
                count: 3,
            },
        ]);
        let newState = orderReducer(initialState, actionSetProducts);

        const actionDecreaseProduct = actions.decreaseProduct(1);
        newState = orderReducer(newState, actionDecreaseProduct);

        expect(
            newState.currentOrder.products.find((product) => product.id === 1)
                ?.count,
        ).toBe(2);
    });

    it('test set pay method - card for current order', () => {
        const action = actions.setPayMethod(PaymentMethods.CARD);
        const newState = orderReducer(initialState, action);

        expect(newState.currentOrder.payMethod).toBe(PaymentMethods.CARD);
    });

    it('test set city', () => {
        const action = actions.setCity('Penza');
        const newState = orderReducer(initialState, action);

        expect(newState.currentOrder.city).toBe('Penza');
    });

    it('test set current page', () => {
        const action = actions.setCurrentPage(10);
        const newState = orderReducer(initialState, action);

        expect(newState.currentPage).toBe(10);
    });

    it('test set page size', () => {
        const action = actions.setPageSize(15);
        const newState = orderReducer(initialState, action);

        expect(newState.pageSize).toBe(15);
    });

    it('test set is completed', () => {
        const action = actions.setIsCompleted();
        const newState = orderReducer(initialState, action);

        expect(newState.isCompleted).toBeTruthy();
    });

    it('test set recipient', () => {
        const action = actions.setRecipient({
            surname: 'Ivanov',
            name: 'Andrey',

            email: 'andrey@mail.ru',
            phone: '+7(999)999-99-99',

            agree: false,
        });
        const newState = orderReducer(initialState, action);

        expect(newState.currentOrder.recipient.surname).toBe('Ivanov');
        expect(newState.currentOrder.recipient.name).toBe('Andrey');
        expect(newState.currentOrder.recipient.email).toBe('andrey@mail.ru');
        expect(newState.currentOrder.recipient.phone).toBe('+7(999)999-99-99');
        expect(newState.currentOrder.recipient.agree).toBeFalsy();
    });

    it('test set receiving method', () => {
        const action = actions.setReceivingMethod({
            method: 'Самовывоз',
            addressSelfPickUp: 'Penza',
            workingTime: 'Пн-Ср 12:00-18:00',
        });
        const newState = orderReducer(initialState, action);

        expect(JSON.stringify(newState.currentOrder.receivingMethod)).toBe(
            JSON.stringify({
                method: 'Самовывоз',
                addressSelfPickUp: 'Penza',
                workingTime: 'Пн-Ср 12:00-18:00',
            }),
        );
    });
});
